Fixing Snapshot coming into the version #
```
    integer_semver = lambda x: [int(elem) for elem in x.split('.')]
ValueError: invalid literal for int() with base 10: '0-SNAPSHOT'
```

ValueError occurs because logic not stripping out non-numeric characters