Artifactory secret3 (#2376)
* GHA: artifactory publish workflow: Set artifactory key from secrets (#2374)

## Summary
1. Why: artifactory artifacts publishing is currently broken due to invalid credentials.
2. What: updates artifactory publish workflow to use secret token.

## Expected Behavior
- publish workflow works 

## Actual Behavior
- publish workflow [fails](https://github.com/linkedin/cruise-control/actions/runs/26465576063/job/77924797384)

## Known Workarounds
- n/a

## Additional evidence
```
$ TOKEN=**** curl -H "Authorization: Bearer $TOKEN" -X GET "https://linkedin.jfrog.io/artifactory/api/system/ping"
OK
```

## Categorization
- [ ] documentation
- [ ] bugfix
- [ ] new feature
- [ ] refactor
- [x] security/CVE
- [ ] other

* GHA: artifactory publish workflow: set artifactory key from secrets (#2375)

## Summary
1. Why: artifactory publishing is still broken, due to invalid username
2. What: username is required and must be a valid one: use 

## Expected Behavior
- artifactory publishing is working

## Actual Behavior
- artifactory publishing is [broken](https://github.com/linkedin/cruise-control/actions/runs/26468260356)

```
Execution failed for task ':artifactoryDeploy'.
> java.io.IOException: JFrog service failed. Received 401: {
    "errors" : [ {
      "status" : 401,
      "message" : "Unauthorized"
    } ]
  }
```

## Steps to Reproduce
https://github.com/linkedin/cruise-control/actions/runs/26468260356

## Known Workarounds
- n/a

## Categorization
- [ ] documentation
- [ ] bugfix
- [ ] new feature
- [ ] refactor
- [x] security/CVE
- [ ] other

This PR resolves #<Replace-Me-With-The-Issue-Number-Addressed-By-This-PR> if any.